name: Mac OSX

on: 
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  release:
    types:
      - created

jobs:
  "unittest_reveng_paj7620":
     runs-on: macos-latest
     steps:
       - uses: actions/checkout@v2
       - uses: ruby/setup-ruby@v1
         with:
           ruby-version: 2.6
       - name: Run tests
         run: |
           g++ -v
           bundle install
           bundle exec arduino_ci.rb
